config/routes.rb
Server::Application.routes.draw do

  resource :balance_sheet, controller: "balance_sheets"
  resources :plane_statistics, controller: "plane_statistics"
  resources :financial_accounts do
    resource :overview, :controller => "financial_account_overviews"
  end

  resource :training_statistic, controller: 'training_statistics', only: [:new, :create]
  resource :destatis_stats, controller: 'destatis_stats', only: [:new, :create]
  resource :blsv_statistics, controller: 'blsv_statistics', only: [:new, :create]

  match '/logout', :to => 'account_sessions#destroy'
  match '/login', :to => 'account_sessions#new'
  match 'dashboard', :to => 'dashboards#show'
  match 'duplicate_check', to: 'duplicate_dashboard#show'

  resource :bordbook

  resources :groups do
    resource :cost_overview, only: [:show] do
      post :settle, on: :member
    end
    resources :people
  end
  resources :headers, :only => [:index]
  resources :people do
    collection do
      post 'import'
      get 'status_list'
    end
    resources :person_cost_category_memberships
    resources :licenses
    resources :financial_account_ownerships
    resource :merge, only: [:create]
  end
  resources :accounts do
    resource :password, :only => [ :new, :create ]
  end
  resource :password, :only => [ :new, :create ]
  resources :account_sessions
  resources :flights do
    resource :launch
    resources :liabilities
    resources :accounting_entries
  end

  match ":filter_model/:filter_id/flights", to: "flights#index"
  match ":filter_model/:filter_id/flights/range/:range/search/:search", to: "flights#index"
  match ":filter_model/:filter_id/flights/range/:range", to: "flights#index"
  match ":filter_model/:filter_id/flights/search/:search", to: "flights#index"
  match "/flights/range/:range/search/:search", to: "flights#index"
  match "/flights/range/:range", to: "flights#index"
  match "/flights/search/:search", to: "flights#index"

  resources :accounting_entries do
    resource :destroy_confirmation
  end
  resources :accounting_sessions do
    resource :destroy_confirmation
    resources :manual_accounting_entries do
      post :import, on: :collection
    end
    resources :flights, :controller => 'accounting_session_flights'
    resources :exclusions, only: [ :create, :destroy ]
  end
  resources :planes do
    collection do
      post 'import'
    end
    resources :plane_cost_category_memberships
    resources :financial_account_ownerships
    resource :merge, only: [:create]
  end
  resources :airfields do
    resource :main_log_book, :only => [:show], :controller => "pdfs"
    resource :merge, only: [:create]
  end
  resources :wire_launchers do
    resources :wire_launcher_cost_category_memberships
    resources :financial_account_ownerships
    resource :log_book, controller: "wire_launcher_log_books"
  end

  resources :person_cost_categories
  resources :plane_cost_categories
  resources :wire_launcher_cost_categories
  resources :person_cost_category_memberships
  resources :plane_cost_category_memberships
  resources :liabilities
  resources :wire_launcher_cost_category_memberships
  resources :flight_cost_rules do
    resources :cost_rule_conditions
    resources :flight_cost_items
  end
  resources :flight_cost_items
  resources :cost_rule_conditions
  resources :cost_hint_conditions, :controller => "cost_rule_conditions"
  resources :number_cost_rule_conditions, :controller => "cost_rule_conditions"
  resources :purpose_cost_rule_conditions, :controller => "cost_rule_conditions"
  resources :wire_launch_cost_rules do
    resources :cost_rule_conditions
    resources :wire_launch_cost_items
  end
  resources :wire_launch_cost_items
  resources :financial_account_ownerships

  resources :cost_rules
  resources :cost_hints
  resources :licenses
  resources :legal_plane_classes
  resource :unknown_person
  resource :own_financial_account, :controller => "financial_account_overviews"

  resources :pdfs
  resources :csvs

  resources :debitors, only: :index

  root :to => 'dashboards#show'

  match "/flights/day/:day_parse_date", :controller => "flights", :action => "index"
  match "/flights_summary(/:date_parse_date)", :controller => "summaries", :action => "show"
  match "/:controller(/:action(/:id))(.:format)"
end

app/models/liability.rb
class Liability < ActiveRecord::Base
  include UuidHelper
  include ImmutableFlight

  flight_relation :flight

  after_save :invalidate_flight
  after_destroy :invalidate_flight

  belongs_to :flight
  belongs_to :person

  validates_presence_of :flight, :person, :proportion
  validates_numericality_of :proportion, :greater_than => 0
  
  def value
    flight.value_for(self)
  end

  def default?
    false
  end

private
  def invalidate_flight
    flight.invalidate_accounting_entries
  end
end

app/controllers/liabilities_controller.rb
class LiabilitiesController < ResourceController
  #before_filter :login_required  
  nested :flight

  def destroy
    model_by_id
    @nested = Flight.find(params[:flight_id])
    @model.destroy
    respond_to do |format|
      format.json { head :ok }
    end
  end  
end

app/views/liabilities/_list.html.haml
.inline_form_replace_context
  %ul.no_bullet
    - flight.liabilities_with_default.each do |l|
      %li.inline_form_hide_context.flight_format
        %span.seat= l.person.name
        %span.time= l.proportion
        %span.time= "#{(flight.proportion_for(l) * 100.0).to_i}%"
        %span= format_currency(l.value)
        - if flight.editable?
          %span= t(".default") if l.default?
          %span= edit_link l, nil, { :class => "inline_form_show", :"data-replace" => flight_liabilities_path(flight) } unless l.default?
          %span= button_to t('views.destroy'), polymorphic_path([flight, l]), :method => :delete, :class => "delete", :"data-replace" => flight_liabilities_path(flight) unless l.default?
  = add_link([flight, Liability], { :class => "inline_form_show", :"data-replace" => flight_liabilities_path(flight) }) if flight.editable?

app/views/liabilities/edit.html.haml
= simple_form_for(@liability) do |f|
  = f.association :flight, :as => :hidden
  = f.association :person
  = f.input :proportion
  = f.button :submit
= link_to t('views.cancel'), @liability.flight, :class => "inline_form_hide"

app/views/liabilities/index.html.haml
= render :partial => "liabilities/list", :locals => { :flight => @nested }

app/views/liabilities/new.html.haml
= simple_form_for(@liability) do |f|
  = f.association :flight, :as => :hidden
  = f.association :person
  = f.input :proportion
  = f.button :submit
= link_to t('views.cancel'), @liability.flight, :class => "inline_form_hide"