config/routes.rb
Server::Application.routes.draw do

  resource :balance_sheet, controller: "balance_sheets"
  resources :plane_statistics, controller: "plane_statistics"
  resources :financial_accounts do
    resource :overview, :controller => "financial_account_overviews"
  end

  resource :training_statistic, controller: 'training_statistics', only: [:new, :create]
  resource :destatis_stats, controller: 'destatis_stats', only: [:new, :create]
  resource :blsv_statistics, controller: 'blsv_statistics', only: [:new, :create]

  match '/logout', :to => 'account_sessions#destroy'
  match '/login', :to => 'account_sessions#new'
  match 'dashboard', :to => 'dashboards#show'
  match 'duplicate_check', to: 'duplicate_dashboard#show'

  resource :bordbook

  resources :groups do
    resource :cost_overview, only: [:show] do
      post :settle, on: :member
    end
    resources :people
  end
  resources :headers, :only => [:index]
  resources :people do
    collection do
      post 'import'
      get 'status_list'
    end
    resources :person_cost_category_memberships
    resources :licenses
    resources :financial_account_ownerships
    resource :merge, only: [:create]
  end
  resources :accounts do
    resource :password, :only => [ :new, :create ]
  end
  resource :password, :only => [ :new, :create ]
  resources :account_sessions
  resources :flights do
    resource :launch
    resources :liabilities
    resources :accounting_entries
  end

  match ":filter_model/:filter_id/flights", to: "flights#index"
  match ":filter_model/:filter_id/flights/range/:range/search/:search", to: "flights#index"
  match ":filter_model/:filter_id/flights/range/:range", to: "flights#index"
  match ":filter_model/:filter_id/flights/search/:search", to: "flights#index"
  match "/flights/range/:range/search/:search", to: "flights#index"
  match "/flights/range/:range", to: "flights#index"
  match "/flights/search/:search", to: "flights#index"

  resources :accounting_entries do
    resource :destroy_confirmation
  end
  resources :accounting_sessions do
    resource :destroy_confirmation
    resources :manual_accounting_entries do
      post :import, on: :collection
    end
    resources :flights, :controller => 'accounting_session_flights'
    resources :exclusions, only: [ :create, :destroy ]
  end
  resources :planes do
    collection do
      post 'import'
    end
    resources :plane_cost_category_memberships
    resources :financial_account_ownerships
    resource :merge, only: [:create]
  end
  resources :airfields do
    resource :main_log_book, :only => [:show], :controller => "pdfs"
    resource :merge, only: [:create]
  end
  resources :wire_launchers do
    resources :wire_launcher_cost_category_memberships
    resources :financial_account_ownerships
    resource :log_book, controller: "wire_launcher_log_books"
  end

  resources :person_cost_categories
  resources :plane_cost_categories
  resources :wire_launcher_cost_categories
  resources :person_cost_category_memberships
  resources :plane_cost_category_memberships
  resources :liabilities
  resources :wire_launcher_cost_category_memberships
  resources :flight_cost_rules do
    resources :cost_rule_conditions
    resources :flight_cost_items
  end
  resources :flight_cost_items
  resources :cost_rule_conditions
  resources :cost_hint_conditions, :controller => "cost_rule_conditions"
  resources :number_cost_rule_conditions, :controller => "cost_rule_conditions"
  resources :purpose_cost_rule_conditions, :controller => "cost_rule_conditions"
  resources :wire_launch_cost_rules do
    resources :cost_rule_conditions
    resources :wire_launch_cost_items
  end
  resources :wire_launch_cost_items
  resources :financial_account_ownerships

  resources :cost_rules
  resources :cost_hints
  resources :licenses
  resources :legal_plane_classes
  resource :unknown_person
  resource :own_financial_account, :controller => "financial_account_overviews"

  resources :pdfs
  resources :csvs

  resources :debitors, only: :index

  root :to => 'dashboards#show'

  match "/flights/day/:day_parse_date", :controller => "flights", :action => "index"
  match "/flights_summary(/:date_parse_date)", :controller => "summaries", :action => "show"
  match "/:controller(/:action(/:id))(.:format)"
end

app/models/wire_launcher.rb
class WireLauncher < ActiveRecord::Base
  include UuidHelper
  include Membership
  include Current
  include AccountingEntryInvalidation

  has_many :wire_launcher_cost_category_memberships
  membership :wire_launcher_cost_category_memberships
  has_many :wire_launches
  has_many :financial_account_ownerships, :as => :owner, :after_add => :association_changed, :after_remove => :association_changed
  has_one_current :financial_account_ownership

  validates_presence_of :registration

  default_scope order("registration asc")
  
  def financial_account
    current_financial_account_ownership && current_financial_account_ownership.financial_account
  end
  
  def financial_account=(fa)
    if new_record?
      financial_account_ownerships << FinancialAccountOwnership.create(:financial_account => fa, :owner => self)
    end
  end
  
  def financial_account_at(date)
    financial_account_ownership_at(date) && financial_account_ownership_at(date).financial_account
  end
  
  def financial_account_id
    financial_account && financial_account.id
  end
  
  def financial_account_id=(fa)
    self.financial_account = FinancialAccount.find(fa)
  end
  
  def to_s
    registration
  end
  
  def find_concerned_accounting_entry_owners(&blk)
    blk ||= lambda { |r| r }
    blk.call(wire_launches)
  end

  def to_j
    { :id => id, :registration => registration }
  end
private
  def association_changed(obj = nil)
    invalidate_concerned_accounting_entries unless new_record?
  end
end

app/controllers/wire_launchers_controller.rb
class WireLaunchersController < ResourceController 
  javascript :lala, :timepicker
end

app/views/wire_launchers/_form.html.haml
= simple_form_for(wire_launcher) do |f|
  = f.input :registration
  = f.button :submit

app/views/wire_launchers/edit.html.haml
%h1= t 'views.editing', :name => WireLauncher.l
= render :partial => "wire_launchers/form", :locals => { :wire_launcher => @wire_launcher }
= show_link(@wire_launcher)
= back_link(WireLauncher)

app/views/wire_launchers/index.html.haml
%h1= t('.title')
= new_link(WireLauncher)
%table.filtered.table.table-striped.table-hover{ :"data-filter-by" => "filter_string" }
  %thead
    %tr.no_filter.show_on_startup
      %th= t("views.filter_search")
    %tr.no_filter.show_on_startup
      %td= text_field_tag "filter_string"
    %tr.no_filter
      %th= WireLauncher.l(:registration)
      %th= WireLauncher.l :wire_launcher_cost_categories
      %th= WireLauncher.l :financial_account
  %tbody
    - @wire_launchers.each do |wire_launcher|
      %tr{ :"data-filter_string" => wire_launcher.registration.downcase }
        %td= h wire_launcher.registration
        %td=h wire_launcher.current_wire_launcher_cost_category_memberships.map { |c| c.wire_launcher_cost_category.name }.join(", ")
        %td=h wire_launcher.financial_account
        %td= show_link(wire_launcher)
        %td= edit_link(wire_launcher)
        %td= link_to t('log_book'), wire_launcher_log_book_path(wire_launcher)

app/views/wire_launchers/new.html.haml
%h1= t 'views.create', :name => WireLauncher.l
= render :partial => "wire_launchers/form", :locals => { :wire_launcher => @wire_launcher }
= link_to t('views.back'), wire_launchers_path

app/views/wire_launchers/show.html.haml
%h1=h @wire_launcher.registration
= link_to t('log_book'), wire_launcher_log_book_path(@wire_launcher)
= edit_link(@wire_launcher)
= back_link(WireLauncher)
= render :partial => "financial_account_ownerships/list", :locals => { :object => @wire_launcher }
= render :partial => "common/memberships", :locals => { :object => @wire_launcher, :group => :wire_launcher_cost_category }